### ISSUE TITLE
Compilation issue with l3fwd-wo-chksm

### ISSUE THREAD

**Issue by clne215** [P4ELTE/t4p4s#16]
Hi,
I am try to run l3fwd-wo-chksm, but there is a problem with compilation。
```
Error: cannot compile file build/util/gen/parser.h.gen.py
Exception: 'P4Node' object has no attribute 'type_ref'
Traceback (most recent call last):
  File "src/compiler.py", line 286, in generate_code
    exec(code, localvars, localvars)
  File "<string>", line 78, in <module>
AttributeError: 'P4Node' object has no attribute 'type_ref'
Traceback (most recent call last):
  File "src/compiler.py", line 565, in <module>
    main()
  File "src/compiler.py", line 554, in main
    generate_desugared_c(filename, join(base, filename))
  File "src/compiler.py", line 336, in generate_desugared_c
    code = generate_code(filepath, genfile, {'hlir16': hlir})
  File "src/compiler.py", line 286, in generate_code
    exec(code, localvars, localvars)
  File "<string>", line 78, in <module>
AttributeError: 'P4Node' object has no attribute 'type_ref'
Error: P4 to C compilation failed (error code: 1)
```

**Comment by VPetyaa** [comment]
It's already fixed in the current master.
./t4p4s.sh examples/l3fwd-wo-chksm-gen.p4 should be working well.
